name: Pest Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  dependencies:
    runs-on: ubuntu-latest
    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.4'
    - uses: actions/setup-node@v5
      with:
        node-version: 22
    - uses: actions/checkout@v4
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install composer packages
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Install npm packages
      run: npm i
    - name: Vite build
      run: npm run build
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Create Database
      run: |
        mkdir -p database
        touch database/database.sqlite
  profanity-tests:
    runs-on: ubuntu-latest
    needs:
      - dependencies
    steps:
      - name: Check for profanity
        run: ./vendor/bin/pest --profanity
  app-tests:
    runs-on: ubuntu-latest
    needs:
      - dependencies
    steps:
      - name: Unit, Feature, Architecture tests
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: ./vendor/bin/pest --exclude-group=smoke --exclude-group=stress --parallel
  smoke-tests:
    runs-on: ubuntu-latest
    needs:
      - dependencies
    steps:
      - name: Smoke tests
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: ./vendor/bin/pest --group=smoke
  stress-tests:
    runs-on: ubuntu-latest
    needs:
      - dependencies
    steps:
      - name: Smoke tests
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: ./vendor/bin/pest --group=stress
